//! Generated files: record and changeset indexes, and staging documents.
//!
//! Owns the exact text of every file the server generates and the comparison of that
//! text with what is on disk. The index layout is the server's own choice (no template
//! defines it). Does not write files; `lint` (P008) and the write tools use it.
//! Entry points: [`generate`], [`same_text`].

use std::collections::BTreeMap;
use std::path::PathBuf;

use crate::changeset::{Changeset, StagingPlan};
use crate::docs::{Role, Snapshot};
use crate::layout::Family;
use crate::records::{RecId, Records};
use crate::text::{Eol, Source};
use crate::util::relative_link;

/// Whether two documents have the same text once line endings are normalized.
pub fn same_text(a: &Source, b: &Source) -> bool {
    a.to_text_lf() == b.to_text_lf()
}

/// Re-terminates every line of `src` with `eol` (a final line without a newline stays so).
pub fn with_eol(mut src: Source, eol: Eol) -> Source {
    if eol == Eol::CrLf {
        for l in &mut src.lines {
            if l.eol == Eol::Lf {
                l.eol = Eol::CrLf;
            }
        }
    }
    src
}

fn index_source(title: &str, heading: &str, entries: &[(String, Vec<String>)]) -> Source {
    let mut lines: Vec<String> = vec![
        title.to_string(),
        "=".repeat(title.chars().count()),
        String::new(),
        "Generated by the palette server; do not edit by hand.".to_string(),
        String::new(),
        heading.to_string(),
        "-".repeat(heading.chars().count()),
        String::new(),
    ];
    if entries.is_empty() {
        lines.push("None.".to_string());
    }
    for (i, (term, defs)) in entries.iter().enumerate() {
        if i > 0 {
            lines.push(String::new());
        }
        lines.push(term.clone());
        for d in defs {
            lines.push(format!("  {d}"));
        }
    }
    Source::from_lines(&lines, Eol::Lf)
}

fn list_or_none(items: &[String]) -> String {
    if items.is_empty() {
        "none".to_string()
    } else {
        items.join(", ")
    }
}

fn record_index(snap: &Snapshot, records: &Records, fam: Family) -> Source {
    let kind = if fam == Family::Rfc {
        crate::records::RecordKind::Rfc
    } else {
        crate::records::RecordKind::Adr
    };
    let dir = snap.loc.dir_of(fam);
    let mut recs: Vec<(RecId, &crate::records::Record)> = records
        .list
        .iter()
        .filter_map(|r| Records::id_of(r).map(|id| (id, r)))
        .filter(|(id, _)| id.kind == kind)
        .collect();
    recs.sort_by(|a, b| (a.0, &snap.files[a.1.file].name).cmp(&(b.0, &snap.files[b.1.file].name)));
    let mut entries = Vec::new();
    for (id, r) in recs {
        let f = &snap.files[r.file];
        let link = relative_link(&dir, &f.path);
        let term = format!("`{id} <{link}>`_ {}", r.title.trim());
        let status = r.status.clone().unwrap_or_else(|| "unknown".to_string());
        let implementation = r
            .field("Implementation")
            .map(|f| f.value.split(" — ").next().unwrap_or("").trim().to_string())
            .unwrap_or_else(|| "unknown".to_string());
        let depends: Vec<String> = r.depends.iter().map(|e| e.id.to_string()).collect();
        let incoming: Vec<String> = records
            .incoming(id)
            .into_iter()
            .map(|(from, k)| format!("{from} ({})", k.label()))
            .collect();
        let sup: Vec<String> = records
            .superseded_by(id)
            .iter()
            .map(|s| s.to_string())
            .collect();
        entries.push((
            term,
            vec![
                format!("Status: {status}. Implementation: {implementation}."),
                format!("Depends: {}.", list_or_none(&depends)),
                format!("Linked from: {}.", list_or_none(&incoming)),
                format!("Superseded by: {}.", list_or_none(&sup)),
            ],
        ));
    }
    let (title, heading) = if fam == Family::Rfc {
        ("Index — RFC", "Records")
    } else {
        ("Index — ADR", "Records")
    };
    index_source(title, heading, &entries)
}

fn changeset_index(
    snap: &Snapshot,
    records: &Records,
    sets: &BTreeMap<RecId, Changeset>,
) -> Source {
    let dir = snap.loc.dir_of(Family::Changeset);
    let mut entries = Vec::new();
    for (id, cs) in sets {
        let f = &snap.files[cs.file];
        let link = relative_link(&dir, &f.path);
        let status = records
            .get(*id)
            .and_then(|r| r.status.clone())
            .unwrap_or_else(|| "no record".to_string());
        let docs: Vec<String> = cs.docs.iter().map(|d| d.doc.clone()).collect();
        entries.push((
            format!("`{id} <{link}>`_"),
            vec![
                format!("Record status: {status}."),
                format!(
                    "Edits: {}. Documents: {}.",
                    cs.edit_count(),
                    list_or_none(&docs)
                ),
            ],
        ));
    }
    index_source("Index — Changesets", "Changesets", &entries)
}

/// Every generated file the project should hold, by absolute path: the `index.rst` of
/// each record and changeset folder that has documents (or already has an index), and
/// one staging document per maintained document with accepted edits.
pub fn generate(
    snap: &Snapshot,
    records: &Records,
    sets: &BTreeMap<RecId, Changeset>,
    plan: &StagingPlan,
) -> BTreeMap<PathBuf, Source> {
    let mut out = BTreeMap::new();
    for fam in [Family::Rfc, Family::Adr, Family::Changeset] {
        let has_docs = snap.files.iter().any(|f| {
            matches!(
                (fam, f.role),
                (Family::Rfc, Role::Rfc)
                    | (Family::Adr, Role::Adr)
                    | (Family::Changeset, Role::Changeset)
            )
        });
        let index_path = snap.loc.index_file(fam);
        let has_index = snap.file(&index_path).is_some();
        if !has_docs && !has_index {
            continue;
        }
        let src = match fam {
            Family::Changeset => changeset_index(snap, records, sets),
            _ => record_index(snap, records, fam),
        };
        out.insert(index_path, src);
    }
    for (logical, staged) in &plan.docs {
        if let Some(path) = snap.loc.staging_file(logical) {
            out.insert(path, staged.source.clone());
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_index_says_none() {
        let s = index_source("Index — RFC", "Records", &[]);
        assert!(s.to_text().ends_with("Records\n-------\n\nNone.\n"));
    }

    #[test]
    fn crlf_conversion_only_touches_terminated_lines() {
        let s = with_eol(Source::from_text("a\nb"), Eol::CrLf);
        assert_eq!(s.to_text(), "a\r\nb");
    }

    #[test]
    fn same_text_ignores_line_endings() {
        assert!(same_text(
            &Source::from_text("a\r\nb\r\n"),
            &Source::from_text("a\nb\n")
        ));
        assert!(!same_text(
            &Source::from_text("a\n"),
            &Source::from_text("b\n")
        ));
    }
}
